app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#sonata
admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin