# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_SUPER_ADMIN:    ROLE_ADMIN
            ROLE_ADMIN:          ROLE_USER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [fos_user, in_memory]

        gitsecret_user_provider:
            id: gitsecret_user_provider

        fos_user:
                id: fos_user.user_provider.username_email

        in_memory:
            memory:
                users:
                   dev: { password: '%password_dev%', roles: ROLE_SUPER_ADMIN }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        git_post:
            pattern: ^/payload
            stateless: true
            simple_preauth:
                authenticator: gitsecret_authenticator
            provider: gitsecret_user_provider

        main:
             pattern: ^/

             form_login:
                 provider: chain_provider
#                 provider: fos_userbundle
                 csrf_token_generator: security.csrf.token_manager
                 default_target_path: admin_dashboard
             logout:
                 path:   /logout
                 target: /login
             anonymous:    true

    access_control:
        # allow enter login url
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/config, roles: !php/const:AppBundle\Entity\User::ROLE_SUPER_ADMIN }

#        # protect everything
        - { path: ^/, roles: !php/const:AppBundle\Entity\User::ROLE_DEFAULT }
