# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            !php/const:AppBundle\Entity\User::ROLE_SUPER_ADMIN:    !php/const:AppBundle\Entity\User::ROLE_ADMIN
            !php/const:AppBundle\Entity\User::ROLE_ADMIN:          !php/const:AppBundle\Entity\User::ROLE_DEFAULT
            !php/const:AppBundle\Entity\User::ROLE_DEPLOY:         !php/const:AppBundle\Entity\User::ROLE_DEFAULT

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        ## Backend
        backend_static:
            memory:
                users:
                   dev:    { password: '%password_dev%', roles: !php/const:AppBundle\Entity\User::ROLE_SUPER_ADMIN }

        backend_fos_user:
                id: fos_user.user_provider.username_email

        username_provider:
            chain:
                providers: [backend_fos_user, backend_static]

        ## Payload
        githook_user_provider:
            id: app.git_username_user_provider

#        deploy_fos_user:
#            entity:
#                class: AppBundle:User
#                property: githubUsername

        deploy_static:
            memory:
                users:
                   deploy: { password: '%password_dev%', roles: !php/const:AppBundle\Entity\User::ROLE_DEPLOY }

        github_username_provider:
            chain:
#                providers: [githook_user_provider, deploy_static]
                providers: [deploy_static, githook_user_provider ]


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        payload:
            pattern: ^/payload
            stateless: true
            provider: github_username_provider
#            provider: deploy_static
            guard:
              entry_point: app.ping_deploy_authenticator
#              entry_point: app.githook_authenticator
              authenticators:
                  - app.githook_authenticator
                  - app.ping_deploy_authenticator

        main:
             pattern: ^/
             form_login:
                 provider: username_provider
#                 provider: fos_userbundle
                 csrf_token_generator: security.csrf.token_manager
                 default_target_path: admin_dashboard
             logout:
                 path:   /logout
                 target: /login
             anonymous:    true

    access_control:
        # allow enter login url
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/config, roles: !php/const:AppBundle\Entity\User::ROLE_SUPER_ADMIN }

#        # protect everything
        - { path: ^/, roles: !php/const:AppBundle\Entity\User::ROLE_DEFAULT }
