services:
    app.admin.pipeline:
        class: AppBundle\Admin\PipelineAdmin
        arguments: [~, AppBundle\Entity\Pipeline, AppBundle:PipelineAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pipeline }

    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
