services:
    # Log ------------------------------------------------
    mysql_log_handler:
        class:  AppBundle\Services\MySQLogHandler
        arguments: ['@doctrine', "@security.token_storage"]

  # Event Listeners ---------------------------------------
    app.ajax_listener:
        class: AppBundle\EventListener\AjaxListener
        tags:
           - { name: kernel.event_subscriber }

    app.user_locale_listener:
        class: AppBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
           - { name: kernel.event_subscriber }

    # deploy payload builder
    app.git_listener:
            class: AppBundle\EventListener\GitListener
    #            arguments: ['%tokens%']
            tags:
#                - { name: kernel.event_listener, event: kernel.request, method: onKernelController, priority: 100 }
                - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    # authentication ---------------------------------
    app.githook_authenticator:
            class:  AppBundle\Security\GitHookAuthenticator
            public: false

    app.git_username_user_provider:
            class: AppBundle\Security\GitSecretUserProvider
            arguments:
                - '@app_user_repository'

    app.ping_deploy_authenticator:
            class:  AppBundle\Security\PingDeployAuthenticator
            arguments:
                - '@security.password_encoder'
            public: false

    # Repositories ---------------------------------------
    app_user_repository:
            class: AppBundle\Repository\UserRepository
            factory: ["@doctrine", getRepository]
            arguments:
                - 'AppBundle:User'

    app_pipeline_repository:
            class: AppBundle\Repository\PipelineRepository
            factory: ["@doctrine", getRepository]
            arguments:
                - 'AppBundle:Pipeline'


  # Menu -------------------------------------------------
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@security.authorization_checker"]
        tags:
            - { name: knp_menu.menu_builder, method: dashboardSidebar, alias: dashboard_sidebar_menu }
